
from big_ol_pile_of_manim_imports import *
class Pembukaan(Scene): 
    def construct(self): 
        text = TextMobject("Project Manim- PDB (PERSAMAAN GELOMBANG)")
        text.to_edge(UP)
        self.play(Write(text))
        self.wait(2)
        text2 = TextMobject("Metode Matematika Oseanografi II (OS2205-01)")
        self.play(Write(text2))
        self.wait(2)

class WriteText(Scene):
    def construct(self):
        text3 = TexMobject("Kelompok 13")
        text3.to_edge(UP)
        self.play(Write(text3))
        self.wait(2)
        nama1 = TexMobject ("Ghaida Nabilah(12917008)")
        nama2 = TexMobject ("Agus Suryadi(12917036)")
        nama2.next_to(nama1,DOWN)
        nama3 = TexMobject ("Isnisari Karina(12918004)")
        nama3.next_to(nama2,DOWN)
        nama4 = TexMobject ("Alexander Wanimbo(12918010)")
        nama4.next_to(nama3,DOWN)
        nama5 = TexMobject ("Abimanyu Yudha(12918025)")
        nama5.next_to(nama4,DOWN)
        self.play(Write(nama1))
        self.wait(0.5)
        self.play(Write(nama2))
        self.wait(0.5)
        self.play(Write(nama3))
        self.wait(0.5)
        self.play(Write(nama4))
        self.wait(0.5)
        self.play(Write(nama5))
        self.wait(0.5)

class Outline (Scene):
    def construct(self):
        text4 = TexMobject("Outline")
        text4.to_edge(UP)
        self.play(Write(text4))
        self.wait(2)
        dafus1 = TexMobject ("Persamaan Gelombang")
        dafus2 = TexMobject ("Metode Pemisahan Variabel (kasus : persamaan gelombang)")
        dafus2.next_to(dafus1,DOWN)
        dafus3 = TexMobject ("Persamaan Transport")
        dafus3.next_to(dafus2,DOWN)
        dafus4 = TexMobject ("Transport Adveksi")
        dafus4.next_to(dafus3,DOWN)
        dafus5 = TexMobject ("Transport Difusi")
        dafus5.next_to(dafus4,DOWN)
        dafus6 = TexMobject ("Persamaan Gelombang-Adveksi (kasus : d'Alembert Solution)")
        dafus6.next_to(dafus5,DOWN)
        self.play(Write(dafus1))
        self.wait(0.5)
        self.play(Write(dafus2))
        self.wait(0,5)
        self.play(Write(dafus3))
        self.wait(0.5)
        self.play(Write(dafus4))
        self.wait(0.5)
        self.play(Write(dafus5))
        self.wait(0.5)
        self.play(Write(dafus6))
        self.wait(0.5)
class Bagian1(Scene): 
    def construct(self): 
        text = TextMobject("Persamaan Differensial Parsial")
        self.play(Write(text))
        self.wait(2)
        text2 = TexMobject("Persamaan Gelombang")
        text2.next_to(text,DOWN)
        self.play(Write(text2))
        self.wait(2)
class Bagian2(Scene): 
    def construct(self):
        text2 = TexMobject("Persamaan Gelombang")
        text2.to_edge(LEFT)
        self.play(Write(text2))
        self.wait(2)
        eq1 = TextMobject("$$\\frac{\\partial^{2}u}{\\partial t^{2}}=c_{2}\\frac{\\partial^{2}u}{\\partial x^{2}}$$")
        eq1.set_color(YELLOW)
        eq1.next_to(text2,DOWN)
        self.play(Write(eq1))
        self.wait(5)
        arrow = Arrow(DOWN)
        arrow.next_to(eq1,DOWN)
        self.play(Write(arrow))
        self.wait(0)
        text7 = TexMobject("Persamaan Gelombang 1D")
        text7.next_to(arrow,DOWN)
        self.play(Write(text7))
        self.wait(0.5)
        text3 = TexMobject("Persamaan Gelombang")
        text3.to_edge(RIGHT)
        self.play(Write(text3))
        self.wait(2)
        eq2 = TextMobject("$$\\frac{\\partial^{2}u}{\\partial t^{2}}=c_{2}\\left (\\frac{\\partial^{2}u}{\\partial x^{2}}+\\frac{\\partial^{2}u}{\\partial y^{2}}\\right )$$")
        eq2.set_color(YELLOW)
        eq2.next_to(text3,DOWN)
        eq2.to_corner(RIGHT)
        self.play(Write(eq2))
        self.wait(5)
        arrow2 = Arrow(DOWN)
        arrow2.next_to(eq2,DOWN)
        self.play(Write(arrow2))
        self.wait(0)
        text8 = TexMobject("Persamaan Gelombang 2D")
        text8.next_to(arrow2,DOWN)
        self.play(Write(text8))
        self.wait(0.5)
class Bagian3(Scene): 
    def construct(self):
        text2 = TexMobject("Karakteristik Persamaan Gelombang")
        text2.to_edge(LEFT)
        text2.to_corner(UP)
        self.play(Write(text2))
        self.wait(2)
        eq1 = TextMobject("$$Au_{xx}+2Bu_{xy}+Cu_{yy}=f\\, (x,y,u,u_{x},u_{y})$$")
        eq1.set_color(YELLOW)
        eq1.next_to(text2,DOWN)
        self.play(Write(eq1))
        self.wait(5)
        text3 = TexMobject("\\ AC-B^{2}<0")
        self.play(Write(text3))
        self.wait(2)
        arrow2 = Arrow(DOWN)
        arrow2.next_to(text3,DOWN)
        self.play(Write(arrow2))
        self.wait(0)
        text8 = TexMobject("Hiperbolik")
        text8.next_to(arrow2,DOWN)
        self.play(Write(text8))
        self.wait(0.5)
class Bagian4(Scene): 
    def construct(self):
        text2 = TexMobject("Contoh kasus :")
        text2.to_edge(LEFT)
        text2.to_corner(UP)
        self.play(Write(text2))
        self.wait(2)
        text3 = TexMobject("Persamaan Umum:")
        text3.next_to(text2,DOWN)
        self.play(Write(text3))
        self.wait(2)
        eq1 = TextMobject("$$ u_{tt}-c^{2}u_{xx}=0$$")
        eq1.set_color(YELLOW)
        eq1.next_to(text3,RIGHT)
        self.play(Write(eq1))
        self.wait(5)
        eq2 = TextMobject("$$ u\\, (x,t)=p\\, (x-ct)+g\\, (x+ct)$$")
        eq2.set_color(YELLOW)
        eq2.next_to(eq1,DOWN)
        self.play(Write(eq2))
        self.wait(5)
        cara1 = TextMobject("$$ \\cdot u_{tt}-$$")
        cara1.set_color(GREEN)
        self.play(Write(cara1))
        self.wait(0)
        cara2 = TextMobject("$$ c^{2} u_{xx}=0$$")
        cara2.set_color(GREEN)
        cara2.next_to(cara1,RIGHT)
        self.play(Write(cara2))
        self.wait(0)
        arrow2 = Arrow(LEFT)
        arrow2.next_to(cara1,DOWN)
        self.play(Write(arrow2))
        self.wait(0)
        arrow3 = Arrow(RIGHT)
        arrow3.next_to(cara2,DOWN)
        self.play(Write(arrow3))
        self.wait(0)
        eq3 = TextMobject("$$ u_{t}+Cu_{x}=w$$")
        eq3.set_color(YELLOW)
        eq3.next_to(arrow2,DOWN)
        self.play(Write(eq3))
        self.wait(5)
        eq4 = TextMobject("$$ u_{t}-Cu_{x}=v$$")
        eq4.set_color(YELLOW)
        eq4.next_to(arrow3,DOWN)
        eq4.next_to(eq3,RIGHT)
        self.play(Write(eq4))
        self.wait(5)
class Bagian5(Scene): 
    def construct(self):
        eq3 = TextMobject("$$ u_{t}+Cu_{x}=w$$")
        eq3.set_color(YELLOW)
        eq3.to_edge(UP)
        eq3.to_corner(LEFT)
        self.play(Write(eq3))
        self.wait(3)
        eq5 = TextMobject("$$ W_{t}+CW_{x}=0$$")
        eq5.set_color(YELLOW)
        eq5.next_to(eq3,DOWN)
        eq5.to_corner(LEFT)
        self.play(Write(eq5))
        self.wait(3)
        eq6 = TextMobject("$$ \\rightarrow w\\, (x,t)=f\\, (x+ct)$$")
        eq6.set_color(YELLOW)
        eq6.next_to(eq5,DOWN)
        eq6.to_edge(LEFT)
        self.play(Write(eq6))
        self.wait(3)
        eq7 = TextMobject("$$ \\rightarrow u_{t}+Cu_{x}=f\\, (x+ct)$$")
        eq7.set_color(YELLOW)
        eq7.next_to(eq6,DOWN)
        eq7.to_edge(LEFT)
        self.play(Write(eq7))
        self.wait(3)
        eq4 = TextMobject("$$ u_{t}-Cu_{x}=v$$")
        eq4.set_color(YELLOW)
        eq4.to_edge(UP)
        eq4.to_corner(RIGHT)
        self.play(Write(eq4))
        self.wait(3)
        eq8 = TextMobject("$$ v_{t}+Cv_{x}=0$$")
        eq8.set_color(YELLOW)
        eq8.next_to(eq4,DOWN)
        eq8.to_corner(RIGHT)
        self.play(Write(eq8))
        self.wait(3)
        eq9 = TextMobject("$$ \\rightarrow V\\, (x,t)=G\\, (x-ct)$$")
        eq9.set_color(YELLOW)
        eq9.next_to(eq8,DOWN)
        eq9.to_edge(RIGHT)
        self.play(Write(eq9))
        self.wait(3)
        eq10 = TextMobject("$$ \\rightarrow u_{t}-Cu_{x}=g\\, (x+ct)$$")
        eq10.set_color(YELLOW)
        eq10.next_to(eq9,DOWN)
        eq10.to_edge(RIGHT)
        self.play(Write(eq10))
        self.wait(3)
        text = TextMobject("$$\\pm $$")
        text.shift(1.25*UP)
        self.play(Write(text))
        eq11 = TextMobject("$$ \\cdot u_{t}=\\frac{1}{2}f\\, (x+ct)+\\frac{1}{2}g\\, (x-ct)$$")
        eq11.set_color(PINK)
        eq11.next_to(eq7,DOWN)
        eq11.to_corner(LEFT)
        self.play(Write(eq11))
        self.wait(3)
        eq12 = TextMobject("$$ \\cdot u_{x}=\\frac{1}{2c}f\\, (x+ct)-\\frac{1}{2c}g\\, (x-ct)$$")
        eq12.set_color(PINK)
        eq12.next_to(eq11,DOWN)
        eq12.to_corner(LEFT)
        self.play(Write(eq12))
        self.wait(3)
class Bagian6(Scene): 
    def construct(self):
        eq3 = TextMobject("F'=f,G'=g")
        eq3.set_color(YELLOW)
        eq3.to_edge(UP)
        eq3.to_corner(LEFT)
        self.play(Write(eq3))
        self.wait(3)
        eq5 = TextMobject("$$ u_{t}:u\\, (x,t)=\\frac{1}{2c}F\\, (x+ct)-\\frac{1}{2c}G\\, (x-ct)$$")
        eq5.set_color(YELLOW)
        eq5.next_to(eq3,DOWN)
        eq5.to_corner(LEFT)
        self.play(Write(eq5))
        self.wait(3)
        eq6 = TextMobject("$$u_{x}: u\\, (x,t)=\\frac{1}{2c}F\\, (x+ct)-\\frac{1}{2c}G\\, (x-ct)$$")
        eq6.set_color(YELLOW)
        eq6.next_to(eq5,DOWN)
        eq6.to_corner(LEFT)
        self.play(Write(eq6))
        self.wait(3)
        text2 = TexMobject("Kesimpulan :")
        text2.to_edge(LEFT)
        self.play(Write(text2))
        self.wait(2)
        eq6 = TextMobject("$$ u\\, (x,t)=\\frac{1}{2c}F\\, (x+ct)+\\frac{-1}{2c}G\\, (x-ct)$$")
        eq6.set_color(PINK)
        eq6.next_to(text2,DOWN)
        eq6.to_corner(LEFT)
        self.play(Write(eq6))
        self.wait(3)
class Bagian7(Scene): 
    def construct(self): 
        text = TextMobject("Persamaan Transpor Adveksi")
        self.play(Write(text))
        self.wait(2)
class Bagian8(Scene): 
    def construct(self):
        text2 = TexMobject("Persamaan Transport")
        text2.to_edge(UP)
        text2.to_corner(LEFT)
        self.play(Write(text2))
        self.wait(2)
        eq1 = TextMobject("$$ u_{t}+Cu_{x}=0$$")
        eq1.set_color(YELLOW)
        eq1.next_to(text2,RIGHT)
        self.play(Write(eq1))
        self.wait(2)
        text3 = TexMobject("saat")
        text3.to_edge(LEFT)
        text3.next_to(text2,DOWN)
        self.play(Write(text3))
        self.wait(1)
        eq2 = TextMobject("$$ v_{t}=0$$")
        eq2.set_color(YELLOW)
        eq2.next_to(text3,RIGHT)
        self.play(Write(eq2))
        self.wait(2)
        text4 = TexMobject("Bergerak_di_koordinat \\rightarrow\\xi = x-ct")
        text4.next_to(text3,DOWN)
        text4.to_edge(LEFT)
        self.play(Write(text4))
        self.wait(1)
        eq6 = TextMobject("$$\\cdot u\\, (x,t)=v\\, (\\xi,t) $$")
        eq6.set_color(YELLOW)
        eq6.next_to(text4,DOWN)
        eq6.to_corner(LEFT)
        eq6.shift(0.5*DOWN)
        self.play(Write(eq6))
        self.wait(3)
        eq7 = TextMobject("$$ \\rightarrow u_{t}=\\frac{\\partial v}{\\partial\\xi}(-c)+\\frac{\\partial v}{\\partial t}u\\, (x,t)= v\\, (\\xi,t)$$")
        eq7.set_color(PINK)
        eq7.next_to(eq6,DOWN)
        eq7.to_corner(LEFT)
        self.play(Write(eq7))
        self.wait(3)
        eq8 = TextMobject("$$ \\rightarrow u_{x}=\\frac{\\partial v}{\\partial\\xi}$$")
        eq8.set_color(PINK)
        eq8.next_to(eq7,DOWN)
        eq8.to_corner(LEFT)
        self.play(Write(eq8))
        self.wait(3)
        eq9 = TextMobject("$$ \\cdot u_{t}+Cu_{x}=$$")
        eq9.set_color(PINK)
        eq9.next_to(eq8,DOWN)
        eq9.to_corner(LEFT)
        self.play(Write(eq9))
        self.wait(0)
        eq10 = TextMobject("$$ -Cv_{\\xi}+$$")
        eq10.set_color(PINK)
        eq10.next_to(eq9,RIGHT)
        self.play(Write(eq10))
        self.wait(0)
        eq11 = TextMobject("$$v_{t}+Cv_{\\xi}=V_{t}$$")
        eq11.set_color(PINK)
        eq11.next_to(eq10,RIGHT)
        self.play(Write(eq11))
        self.wait(0)
class Bagian9(Scene): 
    def construct(self):
        eq9 = TextMobject("$$ \\cdot u_{t}+Cu_{x}=$$")
        eq9.set_color(PINK)
        eq9.to_edge(UP)
        eq9.to_corner(LEFT)
        self.play(Write(eq9))
        self.wait(0)
        eq10 = TextMobject("$$ -Cv_{\\xi}+$$")
        eq10.set_color(PINK)
        eq10.next_to(eq9,RIGHT)
        self.play(Write(eq10))
        self.wait(0)
        eq11 = TextMobject("$$v_{t}+Cv_{\\xi}=V_{t}$$")
        eq11.set_color(PINK)
        eq11.next_to(eq10,RIGHT)
        self.play(Write(eq11))
        self.wait(0)
        arrow2 = Arrow(LEFT)
        arrow2.next_to(eq9,DOWN)
        self.play(Write(arrow2))
        self.wait(0)
        arrow3 = Arrow(RIGHT)
        arrow3.next_to(eq10,DOWN)
        self.play(Write(arrow3))
        self.wait(0)
        eq3 = TextMobject("$$ u_{t}$$")
        eq3.set_color(YELLOW)
        eq3.next_to(arrow2,DOWN)
        self.play(Write(eq3))
        self.wait(1)
        eq4 = TextMobject("$$ u_{x}$$")
        eq4.set_color(YELLOW)
        eq4.next_to(arrow3,DOWN)
        self.play(Write(eq4))
        self.wait(1)
        cara1 = TextMobject("$$ \\cdot usual_coords : (x,t) \\rightarrow u\\,(x,t)$$")
        cara1.set_color(GREEN)
        cara1.next_to(eq4,DOWN)
        cara1.to_edge(LEFT)
        self.play(Write(cara1))
        self.wait(1)
        cara2 = TextMobject("$$ u_{t}+Cu{x}=0$$")
        cara2.set_color(GREEN)
        cara2.next_to(cara1,2*RIGHT)
        self.play(Write(cara2))
        self.wait(1)
        cara3 = TextMobject("$$ \\cdot Moving_coords : (\\xi,t) \\rightarrow v\\,(\\xi,t)$$")
        cara3.set_color(GREEN)
        cara3.next_to(cara2,DOWN)
        cara3.to_edge(LEFT)
        self.play(Write(cara3))
        self.wait(1)
        cara4 = TextMobject("$$ v_{t}=0$$")
        cara4.set_color(GREEN)
        cara4.next_to(cara3,2*RIGHT)
        self.play(Write(cara4))
        self.wait(1)
        cara5 = TextMobject("$$ \\xi=-ct0$$")
        cara5.set_color(GREEN)
        cara5.next_to(cara4,2*RIGHT)
        self.play(Write(cara5))
        self.wait(1)
        cara6 = TextMobject("$$ \\cdot mencari u\\,(x,t) $$")
        cara6.set_color(GREEN)
        cara6.next_to(cara5,DOWN)
        cara6.to_corner(LEFT)
        self.play(Write(cara6))
        self.wait(1)
        cara7 = TextMobject("$$ \\ v_{t}=0 \\rightarrow v=F\\,(\\xi) $$")
        cara7.set_color(GREEN)
        cara7.next_to(cara6,DOWN)
        cara7.to_corner(LEFT)
        self.play(Write(cara7))
        self.wait(1)
        cara8 = TextMobject("$$ \\ v\\,(\\xi,t)=u\\,(x,t) \\rightarrow u\\,(x,t)=F\\,(xi)=F\\,(x-ct) $$")
        cara8.set_color(GREEN)
        cara8.next_to(cara7,DOWN)
        cara8.to_corner(LEFT)
        self.play(Write(cara8))
        self.wait(1)
        cara9 = TextMobject("$$ kesimpulan \\rightarrow u_{t}+Cu_{x}=0 ,adalah F\\,(x-ct)$$")
        cara9.next_to(cara8,DOWN)
        cara9.to_corner(LEFT)
        self.play(Write(cara9))
        self.wait(1)
class Bagian10(Scene): 
    def construct(self): 
        text = TextMobject("Metode Pemisah Variabel")
        text.to_edge(UP)
        self.play(Write(text))
        self.wait(2)
        eq1 = TextMobject("$$ \\eta_{tt}=c^{2}\\eta_{xx},0<x<L,t>0,,,(1)$$")
        eq1.set_color(YELLOW)
        eq1.next_to(text,DOWN)
        eq1.to_corner(LEFT)
        self.play(Write(eq1))
        self.wait(2)
        text3 = TexMobject("misalkan,\\eta\\,(x,t)=X\\,(x) T,...(2)")
        text3.set_color(YELLOW)
        text3.to_edge(LEFT)
        text3.next_to(eq1,DOWN)
        text3.to_corner(LEFT)
        self.play(Write(text3))
        self.wait(2)
        text4 = TexMobject("masukan persamaan (1) ke persamaan (2):")
        text4.to_edge(LEFT)
        text4.next_to(text3,DOWN)
        text4.to_corner(LEFT)
        self.play(Write(text4))
        self.wait(2)
        text5 = TexMobject("c^{2}X''T=xt''")
        text5.to_edge(LEFT)
        text5.next_to(text4,DOWN)
        self.play(Write(text5))
        self.wait(2)
        text6 = TexMobject("\\frac{X''}{x}\\frac{1}{c^{2}}\\frac{T''}{T}=-\\lambda...(3)")
        text6.to_edge(LEFT)
        text6.next_to(text5,DOWN)
        self.play(Write(text6))
        self.wait(2)
        text7 = TexMobject("menghasilkan ")
        text7.next_to(text6,DOWN)
        text7.to_edge(LEFT)
        self.play(Write(text7))
        self.wait(2)
        text8 = TexMobject("(T'')=\\lambda (x)=0...(4a)")
        text8.next_to(text7,RIGHT)
        self.play(Write(text8))
        self.wait(2)
        text9 = TexMobject("(X'')=c^{2}\\lambda (x)=0...(4b)")
        text9.next_to(text8,DOWN)
        self.play(Write(text9))
        self.wait(2)
class Bagian11(Scene): 
    def construct(self): 
        text = TextMobject("Dengan syarat batas x=0 :")
        text.to_edge(UP)
        self.play(Write(text))
        self.wait(2)
        eq1 = TextMobject("$$ \\eta\\,(0,t)=X\\,(0)T\\,(t)=0$$")
        eq1.set_color(YELLOW)
        eq1.next_to(text,DOWN)
        eq1.to_corner(LEFT)
        self.play(Write(eq1))
        self.wait(3)
        text3 = TexMobject("dengan X(0)=0 \\rightarrow x=L \\rightarrow X(L)=0")
        text3.to_edge(LEFT)
        text3.next_to(eq1,DOWN)
        text3.to_corner(LEFT)
        self.play(Write(text3))
        self.wait(2)
        text4 = TexMobject("\\cdot solusi-umum-persamaan-4a:")
        text4.to_edge(LEFT)
        text4.next_to(text3,DOWN)
        text4.to_corner(LEFT)
        self.play(Write(text4))
        self.wait(2)
        text5 = TexMobject("X(x)=A \\cos (\sqrt{\\lambda x})+B \\sin (\sqrt{\\lambda x}))")
        text5.set_color(YELLOW)
        text5.next_to(text4,DOWN)
        text5.to_edge(LEFT)
        self.play(Write(text5))
        self.wait(2)
        text6 = TexMobject("\\cdot subtitusi-syarat-batas-dari-fungsi-eigen")
        text6.next_to(text5,DOWN)
        text6.to_edge(LEFT)
        self.play(Write(text6))
        self.wait(2)
        text7 = TexMobject("x_{n}=sin\\frac({n\\pi}{L}X) , n=1,2,3,4,..")
        text7.set_color(YELLOW)
        text7.next_to(text6,DOWN)
        text7.to_edge(LEFT)
        self.play(Write(text7))
        self.wait(2)
class Bagian12(Scene): 
    def construct(self):
        text8 = TexMobject("\\cdot nilai eigen")
        text8.to_edge(UP)
        text8.to_edge(LEFT)
        self.play(Write(text8))
        self.wait(2)
        text9 = TexMobject("\\lambda_{n}=\\frac{n^{2}\\pi^{2}}{L^{2}}.... n=1,2,3,4,...")
        text9.set_color(YELLOW)
        text9.next_to(text8,DOWN)
        text9.to_edge(LEFT)
        self.play(Write(text9))
        self.wait(2)
        text3 = TexMobject("persamaan (4b) dan \\lambda{n}")
        text3.to_edge(LEFT)
        text3.next_to(text9,DOWN)
        self.play(Write(text3))
        self.wait(2)
        text4 = TexMobject("TT''+c^{2}\\frac{n^{2}\\pi^{2}}{L^{2}}T=0....(5)")
        text4.set_color(YELLOW)
        text4.to_edge(LEFT)
        text4.next_to(text3,DOWN)
        text4.to_corner(LEFT)
        self.play(Write(text4))
        self.wait(2)
        text6 = TexMobject("solusi umum ")
        text6.next_to(text4,DOWN)
        text6.to_edge(LEFT)
        self.play(Write(text6))
        self.wait(2)
        text5 = TexMobject("T\\,(t)=A \\cos \\frac{nc\\pi}{L}t+B \\sin \\frac{nc\\pi}{L}t)")
        text5.set_color(YELLOW)
        text5.next_to(text6,DOWN)
        text5.to_edge(LEFT)
        self.play(Write(text5))
        self.wait(2)
        text7 = TexMobject("Syarat awal T'(0)=0")
        text7.next_to(text5,DOWN)
        text7.to_edge(LEFT)
        self.play(Write(text7))
        self.wait(2)
        text8 = TexMobject("T_{n}t=cos \\frac{nc\\pi}{L}")
        text8.set_color(YELLOW)
        text8.next_to(text7,DOWN)
        text8.to_edge(LEFT)
        self.play(Write(text8))
        self.wait(2)
class Bagian13(Scene): 
    def construct(self):
        text8 = TexMobject("solusi persamaan gelombang:")
        text8.to_edge(UP)
        text8.to_edge(LEFT)
        self.play(Write(text8))
        self.wait(2)
        text9 = TexMobject("\\eta_{n}\\,(x,t)=sin\\frac{n\\pi}{L}x.Cos\\frac{nc\\pi}{L}t, n=1,2,3.. ")
        text9.set_color(YELLOW)
        text9.next_to(text8,DOWN)
        text9.to_edge(LEFT)
        self.play(Write(text9))
        self.wait(2)
        text3 = TexMobject("syarat awal ,\\eta\\,(x,0)=f\\,(x) ")
        text3.next_to(text9,DOWN)
        text3.to_edge(LEFT)
        self.play(Write(text3))
        self.wait(2)
        text4 = TexMobject("\\eta\\,(x,t)=\\sum_{n=1}^{\\infty}C_{n}Sin\\frac{n\\pi}{L}x.Cos\\frac{nc\\pi}{L}t...(6)")
        text4.set_color(YELLOW)
        text4.to_edge(LEFT)
        text4.next_to(text3,DOWN)
        text4.to_corner(LEFT)
        self.play(Write(text4))
        self.wait(2)
        text5 = TexMobject("syarat-awal ,\\eta\\,(x,0)=f\\,(x) maka ")
        text5.next_to(text4,DOWN)
        text5.to_edge(LEFT)
        self.play(Write(text5))
        self.wait(2)
        text6 = TexMobject("\\eta\\,(x,t)=\\sum_{n=1}^{\\infty}\\eta_{n}\\,(x,t)=\\sum_{n=1}^{\\infty}C_{n}Sin\\frac{n\\pi}{L}x.Cos\\frac{nc\\pi}{L}t")
        text6.set_color(YELLOW)
        text6.to_edge(LEFT)
        text6.next_to(text5,DOWN)
        text6.to_corner(LEFT)
        self.play(Write(text6))
        self.wait(2)
class Bagian14(Scene): 
    def construct(self):
        text7 = TexMobject("\\eta\\,(x,0)=f\\,(x) maka ")
        text7.to_edge(LEFT)
        text7.to_corner(UP)
        self.play(Write(text7))
        self.wait(2)
        text8 = TexMobject("\\eta\\,(x,t)=\\sum_{n=1}^{\\infty}C_{n}Sin\\frac{n\\pi}{L}x=f\\,(x)")
        text8.set_color(YELLOW)
        text8.to_edge(LEFT)
        text8.next_to(text7,DOWN)
        text8.to_corner(LEFT)
        self.play(Write(text8))
        self.wait(2)
        text5 = TexMobject("c\\,(n) =Koefiseien- deret -fourier")
        text5.next_to(text8,DOWN)
        text5.to_edge(LEFT)
        self.play(Write(text5))
        self.wait(2)
        text4 = TexMobject("\\frac{2}{L}\\int_{0}^{L}f\\,(x).Sin\\frac{n\\pi}{L}x dx")
        text4.set_color(YELLOW)
        text4.to_edge(LEFT)
        text4.next_to(text5,DOWN)
        text4.to_corner(LEFT)
        self.play(Write(text4))
        self.wait(2)
class Bagian15(Scene): 
    def construct(self): 
        text = TextMobject("Kaitan Persamaan Adveksi dan Persamaan Gelombang")
        text.to_edge(UP)
        self.play(Write(text))
        self.wait(2)
        eq1 = TextMobject("$$\\frac{\\partial^{2}u}{\\partial t^{2}}=c^{2}\\frac{\\partial^{2}u}{\\partial x^{2}} ,-\\infty <x<\\infty $$")
        eq1.set_color(YELLOW)
        eq1.next_to(text,DOWN)
        self.play(Write(eq1))
        self.wait(5)
        text2 = TexMobject("Solusi?")
        text2.set_color(BLUE)
        text2.next_to(eq1,DOWN)
        text2.to_edge(LEFT)
        self.play(Write(text2))
        self.wait(2)
        text3 = TexMobject("Dengan Kondisi Awal :")
        text3.next_to(text2,DOWN)
        text3.to_edge(LEFT)
        self.play(Write(text3))
        self.wait(1)
        eq2 = TexMobject("u\, (x,0)=u_{0}x,\\frac{\\partial u}{\\partial t}{t=0}=v_{0}x")
        eq2.set_color(YELLOW)
        eq2.next_to(text3,RIGHT)
        self.play(Write(eq2))
        self.wait(2)
        text4 = TexMobject("Solusi Umum Persamaan Gelombang :")
        text4.next_to(eq2,DOWN)
        text4.to_edge(LEFT)
        self.play(Write(text4))
        self.wait(2)
        eq3 = TexMobject ("u\, (x,t)=f\, (x+ct)+g\, (x-ct)")
        eq3.set_color(YELLOW)
        eq3.next_to(text4,DOWN)
        self.play(Write(eq3))
        self.wait(1.5)
        text5 = TexMobject("Titik Tetap f(0)","&","g(0)")
        text5.next_to(eq3,DOWN)
        text5.to_edge(LEFT)
        self.play(Write(text5))
        self.wait(1.5)
        eq4 = TexMobject("f\, (0)=f\, (x+ct),x=-ct")
        eq4.set_color(YELLOW)
        eq4.next_to(text5,DOWN)
        eq4.to_edge(LEFT)
        self.play(Write(eq4))
        self.wait(3)
class Bagian16(Scene): 
    def construct(self):
        eq5 = TexMobject("g\, (0)=f\, (x-ct),x=ct")
        eq5.set_color(YELLOW)
        eq5.to_edge(UP)
        eq5.to_edge(LEFT)
        self.play(Write(eq5))
        self.wait(1)
        text6 = TexMobject("c=Kecepatan Gelombang , t=Waktu")
        text6.next_to(eq5,DOWN)
        text6.to_edge(LEFT)
        self.play(Write(text6))
        self.wait(1)
        eq6 = TexMobject ("u\, (x,t)=")
        eq6.set_color(YELLOW)
        eq6.to_edge(LEFT)
        self.play(Write(eq6))
        self.wait(1)
        eq8 = TexMobject ("f\, (x+ct)+")
        eq8.set_color(YELLOW)
        eq8.next_to(eq6,RIGHT)
        self.play(Write(eq8))
        self.wait(0)
        arrow = Arrow(DOWN)
        arrow.next_to(eq8,DOWN)
        self.play(Write(arrow))
        self.wait(0)
        text7 = TexMobject("Backward Travelling Waves")
        text7.next_to(arrow,DOWN)
        self.play(Write(text7))
        self.wait(0.5)
        eq7 = TexMobject ("g\, (x-ct)")
        eq7.set_color(YELLOW)
        eq7.next_to(eq8,RIGHT)
        self.play(Write(eq7))
        self.wait(0.5)
        arrow2 = Arrow(DOWN)
        arrow2.next_to(eq7,DOWN)
        self.play(Write(arrow2))
        text8 = TexMobject("Forward Travelling Waves")
        text8.next_to(arrow2,DOWN)
        self.play(Transform(arrow,arrow2))
        self.play(Transform(text7,text8))
        self.play(Write(text8))
        self.wait(1)
class Bagian17(Scene): 
    def construct(self):
        text9 = TextMobject("Solusi Khusus Dari Persamaan Gelombang")
        text9.to_edge(UP)
        text9.to_edge(LEFT)
        self.play(Write(text9))
        self.wait(2)
        cara1 = TextMobject("$$\\cdot t=0,u\\rightarrow (x,0)=u_{0}x$$")
        cara1.set_color(GREEN)
        cara1.next_to(text9,DOWN)
        cara1.to_edge(LEFT)
        self.play(Write(cara1))
        self.wait(1)
        cara11 = TextMobject("$$\\rightarrow u_{0}x=f\\, (x+c.0)+g\\, (x-c.0)$$")
        cara11.set_color(YELLOW)
        cara11.next_to(cara1,DOWN)
        cara11.to_edge(LEFT)
        self.play(Write(cara11))
        self.wait(1)
        cara12 = TextMobject("$$\\rightarrow u_{0}x=f\\, (x)+g\\, (x)...(1)$$")
        cara12.set_color(BLUE)
        cara12.next_to(cara11,DOWN)
        cara12.to_edge(LEFT)
        self.play(Write(cara12))
        self.wait(2)
        cara2 = TextMobject("$$\\cdot\\frac{\\partial u}{\\partial t}=f'\\, (x+ct)(c)+g\\, (x-ct)(-c)$$")
        cara2.set_color(GREEN)
        cara2.next_to(cara12,DOWN)
        cara2.to_edge(LEFT)
        self.play(Write(cara2))
        self.wait(2)
        cara21 = TextMobject("$$t=0\\rightarrow\\frac{\\partial u}{\\partial t}=v_{0}x$$")
        cara21.set_color(YELLOW)
        cara21.next_to(cara2,DOWN)
        cara21.to_edge(LEFT)
        self.play(Write(cara21))
        self.wait(2)
        cara22 = TextMobject("$$\\rightarrow v_{0}x=f'\\, (x+c.0)(c)+g'\\, (x-c.0)(-c)$$")
        cara22.set_color(YELLOW)
        cara22.next_to(cara21,DOWN)
        cara22.to_edge(LEFT)
        self.play(Write(cara22))
        self.wait(1)
        cara23 = TextMobject("$$\\rightarrow v_{0}x=f'\\, (x)c-g'\\, (x)c$$")
        cara23.set_color(YELLOW)
        cara23.next_to(cara22,DOWN)
        cara23.to_edge(LEFT)
        cara24 = TextMobject("$$\\rightarrow v_{0}x=c(f'\\, (x)-g'\\, (x))...(2)$$")
        cara24.set_color(BLUE)
        cara24.next_to(cara23,DOWN)
        cara24.to_edge(LEFT)
        self.play(Write(cara23))
        self.play(Transform(cara23,cara24))
        self.wait(2)
class Bagian18(Scene): 
    def construct(self):
        a = TexMobject("\\cdot\\int_{x_{0}}^{x}{V{_{0}}S dS=c(f\\, (x)-f\\, (x_{0}))-c(g\\, (x)-g\\, (x_{0}))")
        a.set_color(GREEN)
        a.to_edge(UP)
        a.to_edge(LEFT)
        self.play(Write(a))
        self.wait(10)
        b = TextMobject("$$\\rightarrow\\frac{1}{c}$$")
        b.set_color(YELLOW)
        b.next_to(a,DOWN)
        b.to_edge(LEFT)
        self.play(Write(b))
        self.wait(0)
        c = TexMobject("\\int_{x_{0}}^{x}{V{_{0}}S dS+g\\, (x_{0})-f\\, (x_{0})=c(f\\, (x)-c(g\\, (x)...(3)")
        c.set_color(YELLOW)
        c.next_to(b,RIGHT)
        self.play(Write(c))
        self.wait(3)
        d = TextMobject("$$\\cdot Persamaan (1) dan Persamaan (3)$$")
        d.set_color(GREEN)
        d.next_to(c,DOWN)
        d.to_edge(LEFT)
        self.play(Write(d))
        self.wait(10)
        e = TextMobject("$$\\rightarrow f\\,(x)=\\frac{1}{2}u_{o}\\,(x+ct)+\\frac{1}{2c}$$")
        e.set_color(YELLOW)
        e.next_to(d,DOWN)
        e.to_edge(LEFT)
        self.play(Write(e))
        self.wait(1)
        f = TextMobject("$$\\int_{x_{0}}^{x+ct}V_{0}SdS+\\frac{f\\,(x_{0})-g\\,(x_{0})}{2}$$")
        f.set_color(YELLOW)
        f.next_to(e,RIGHT)
        self.play(Write(f))
        self.wait(2)
        g = TextMobject("$$\\rightarrow g\\,(x)=\\frac{1}{2}u_{o}\\,(x-ct)+\\frac{1}{2c}$$")
        g.set_color(YELLOW)
        g.next_to(f,DOWN)
        g.to_edge(LEFT)
        self.play(Write(g))
        self.wait(1)
        h = TextMobject("$$\\int_{x_{0}}^{x-ct}V_{0}SdS+\\frac{f\\,(x_{0})-g\\,(x_{0})}{2}$$")
        h.set_color(YELLOW)
        h.next_to(g,RIGHT)
        self.play(Write(h))
        self.wait(2)
class Bagian19(Scene): 
    def construct(self):
        q = TexMobject("\\cdot Persamaan umum:")
        q.set_color(GREEN)
        q.to_edge(UP)
        q.to_edge(LEFT)
        self.play(Write(q))
        self.wait(1)
        r = TexMobject ("u\\, (x,t)=f\\, (x+ct)+g\\, (x-ct)")
        r.set_color(YELLOW)
        r.next_to(q,RIGHT)
        self.play(Write(r))
        self.wait(6)
        q = TextMobject("$$\\rightarrow u\\, (x,t)=\\frac{1}{2}u_{o}\\,(x+ct)-\\frac{1}{2}u_{o}\\,(x-ct)+$$")
        q.set_color(YELLOW)
        q.next_to(r,DOWN)
        q.to_corner(LEFT)
        self.play(Write(q))
        self.wait(1)
        s = TextMobject("$$\\int_{x-ct}^{x+ct}V_{0}SdS$$")
        s.set_color(YELLOW)
        s.next_to(q,RIGHT)
        self.play(Write(s))
        self.wait(2)
        t = TextMobject("$$\\rightarrow u\\, (x,t)=\\frac{1}{2}(u_{o}\\,(x+ct)-u_{o}\\,(x-ct))+$$")
        t.set_color(BLUE)
        t.next_to(s,DOWN)
        t.to_corner(LEFT)
        self.play(Write(t))
        self.wait(1)
        u = TextMobject("$$\\int_{x-ct}^{x+ct}V_{0}SdS$$")
        u.set_color(BLUE)
        u.next_to(t,RIGHT)
        self.play(Write(u))
        self.wait(2)
        panah1 = Arrow(DOWN)
        panah1.next_to(t,DOWN)
        self.play(Write(panah1))
        self.wait(1)
        v = TextMobject ("D'Alembert Solution")
        v.next_to(panah1,DOWN)
        self.play(Write(v))
        self.wait(6)


